### ISSUE TITLE
Python error in install

### ISSUE THREAD

**Issue by anthrolisp** [brettkromkamp/contextualise#1]
Hi, This looks really interesting. I keep getting the following error while attempting to install the development version. 

`
 ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sjgw80/topic-db/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sjgw80/topic-db/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-sjgw80/topic-db/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sjgw80/topic-db/setup.py", line 13, in <module>
        with open(os.path.join(here, 'README.rst'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`
I'm on Ubuntu 19.94 . Any ideas? Thanks in advance!

**Comment by brettkromkamp** [comment]
That looks to me like you are trying to install Contextualise with Python 2: the ‘open’ function in Python 2 does not include the ‘encoding’ parameter. The minimum Python version to install Contextualise is 3.6. Please try with Python 3.6+ and let me know if you have problems. Don’t forget that you have to separately set up the database for the application.

**Comment by brettkromkamp** [comment]
Brief instructions on how to set up the TopicDB/Contextualise database are provided, here: [Setting up the TopicDB database](https://gist.github.com/brettkromkamp/87aaa99b056578ff1dc23a43a49aca89). You need to ensure that the database username, password and database name match with the settings.ini file in the project's root folder.

**Comment by machawk1** [comment]
I have both Python 2 and 3 installed. @anthrolisp might want to try running the `pip` command with `pip3` instead if Python 3 is in fact installed.

**Comment by brettkromkamp** [comment]
@anthrolisp Before installing Contextualise, you have to have certain build prerequisites in place including a C-compiler, the Python header files, the `libpq` header files and the `pg_config` program as outlined here: [Build prerequisites](http://initd.org/psycopg/docs/install.html#build-prerequisites). This is not ideal and I am currently considering how to dockerize Contextualise (#2) to get users up and running quicker.
