### ISSUE TITLE
Modules in Contextualise 

### ISSUE THREAD

**Issue by imthevs** [brettkromkamp/contextualise#103]
Contextualise can have 'modules'.  Features that could be considered 'optional' or 'standalone' could be moved to these modules.  Users could optionally download and enable/disable these modules. 

For example, the 3D images viewing feature may not be used by a lot of users (speculating here).  So this feature could be moved to an optional '3D Module'. 

An alternate term you could consider for a 'module' is a 'plugin'. 

This will, of course, open up this product to a lot of collaborators who could contribute their own plugins.

**Comment by brettkromkamp** [comment]
@imthevs Hi :) I would love to have a (user-facing) plug-in system for Contextualise. I’m away from my computer at the moment, but I will follow up on this matter with you this weekend. Do you have anything specific in mind?

**Comment by brettkromkamp** [comment]
@imthevs I am reviewing several (user-facing) plug-in approaches for Flask applications and I hope to land on something soon. In the mean-time, if you have any suggestions I'm all ears :)

**Comment by imthevs** [comment]
I don't have anything to add here, I'm afraid.  But I'd be very happy to help with user testing.
