### ISSUE TITLE
Automatically Fix Associations on Rename

### ISSUE THREAD

**Issue by redcitylights** [brettkromkamp/contextualise#106]
Currently when a topic is renamed it breaks associations involving that topic.  This could be fixed automatically

**Comment by brettkromkamp** [comment]
@redcitylights Hi. Could you explain the issue? The reason I ask is that topic names (plural: a topic can have one or more names) are independent from the topic identifier. Renaming a topic changes the name but never the identifier: topic identifiers cannot be changed. Topic identifiers are used as part of an association not the topic name. So, renaming a topic will not break associations of which the topic is part of.

Are you perhaps referring to **links** in, for example, topic texts or notes? In that case, renaming a topic will not automagically update the anchor text of the corresponding links.
