### ISSUE TITLE
Cannot login or reset my password

### ISSUE THREAD

**Issue by navigator8** [brettkromkamp/contextualise#143]
Cannot login or reset my password: my handle: flchambati at hotmail dot com

**Comment by brettkromkamp** [comment]
At some point, a couple of months back, as part of a huge upgrade to Contextualise, all of the existing test data was dropped. However, we could restore your topic maps from a backup (with some work).

**Comment by navigator8** [comment]
Hi Brett,

Not to worry, I was prepared for loss of data. I was hoping it was just a password issue.

Let’s close the topic.

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by brettkromkamp** [comment]
Would you consider self-hosting (i.e., installing Contextualise locally on your machine)? It really is pretty straightforward to install Contextualise. I can help if necessary :-)
