### ISSUE TITLE
Add UI support for tagging

### ISSUE THREAD

**Issue by brettkromkamp** [brettkromkamp/contextualise#16]
Adding, removing and visualizing (i.e., tag cloud) tags using the appropriate (topic maps) association types and roles.

**Comment by weaversam8** [comment]
+1 on this - I think the ability to capture information _quickly_ is something that's very important, and being forced to choose a topic at the moment where you input a note isn't necessarily the only way to do it.

If I could jot down a plaintext note with #hashtags that would then suggest some relevant links (topical, to other notes, etc) to make later, that would be a great feature to reduce the friction to bring information into Contextualise.

**Comment by brettkromkamp** [comment]
@weaversam8 Check out this repo for an updated list of applications (personal) knowledge management, note-taking, etc.: https://github.com/brettkromkamp/knowledge-graph-radar

Specifically, [Roam Research](https://roamresearch.com/) and [TiddlyWiki](https://tiddlywiki.com/) are very powerful and allow for quick info ingestion and (back)linking.

Anyway, semantic tagging support has been bumped into 1.0.0 (before, 1.1.0).

**Comment by weaversam8** [comment]
@brettkromkamp - this is fantastic! Bookmarking this repo for later!

**Comment by brettkromkamp** [comment]
@weaversam8 Hope Contextualise proves useful to you :)

**Comment by brettkromkamp** [comment]
Ongoing support for associative tagging: https://github.com/brettkromkamp/contextualise/commit/5c5994f9db1cf5711aca3ab30b0685fd16f53e13

![contextualise-tagged-topic](https://user-images.githubusercontent.com/160078/85230177-bf391900-b3ee-11ea-93a5-0081d900d23d.png)
![contextualise-tag-topic](https://user-images.githubusercontent.com/160078/85230179-c06a4600-b3ee-11ea-84a8-529db33f1e84.png)
![contextualise-tag-topic](https://user-images.githubusercontent.com/160078/85230181-c102dc80-b3ee-11ea-9509-d76c32b21d54.png)
![contextualise-tagged-topic](https://user-images.githubusercontent.com/160078/85230182-c19b7300-b3ee-11ea-905f-f2508568989f.png)

**Comment by brettkromkamp** [comment]
@navigator8 This feature is now complete. This is associative tagging meaning that the tag becomes a topic with an association to connect the topic that is being tagged and the resulting "tag topic". If you have time, play around with it a bit and let me know what you think.
