### ISSUE TITLE
Implement topics index

### ISSUE THREAD

**Issue by brettkromkamp** [brettkromkamp/contextualise#17]
An index (list) of all topics in a given topics map with pagination.

**Comment by navigator8** [comment]
What is the status if this topic.

**Comment by brettkromkamp** [comment]
@navigator8 I'm currently working on https://github.com/brettkromkamp/contextualise/issues/33 which I hope to finish in a couple of days. Once done, I could bump this issue's version number (from 1.1 to 1.0) and move on to working on that. You're asking because it is an import feature for you?

**Comment by navigator8** [comment]
@brettkromkamp  I Brett - this one is super important for me. Here is the Use Case. I create topics as they come to me  - empty my brain.  Then I start to associate them as second step. I have realised without Topic index - I have not way of knowing the topics I have in my map.

Secondly, I read your block on different Association Types and Roles - that is very good. I also realised you created some automatically in a map - I bumped into Categorisation.

**Comment by brettkromkamp** [comment]
@navigator8 I understand your use case :) Okay, I will probably increase the priority of the topics index feature (put it into version 1.0). With regards to capturing topics first and then associating them later, Contextualise has a feature for that: top-level notes. Take a look, here: https://contextualise.dev/notes/index/44. Here you can see a couple of notes that I have added to a topic map. After you have created a set of notes ("emptying your brain" as you call it) you can do one of two things with each note: 1) attach the note to an already existing topic (as a comment), or 2) convert the note into a (stand-alone) topic after which you can associate the topic as you see fit.

The attached screen shot shows the notes index when logged in with the options I mentioned above.

![notes-view](https://user-images.githubusercontent.com/160078/81492346-22377c00-9297-11ea-98b0-94f1f0274259.png)

**Comment by brettkromkamp** [comment]
@navigator8 Also, take a look at the Knowledge Graph Radar to see which other applications could be of use to you (to map knowledge): https://github.com/brettkromkamp/knowledge-graph-radar#applications

**Comment by navigator8** [comment]
This resource is gold. I am familiar with Roam, Tiddlywiki (specifically Tiddlymap.org), Notion. I am still on the waiting list for: KgBase<https://kgbase.com/>

Two more to add to the list: Kumu and https://pengloo.com/<https://pengloo.com/p>

Many thanks

---

Msny om: Brett Alistair Kromkamp <notifications@github.com>
Sent: Sunday, 10 May 2020 4:28 PM
To: brettkromkamp/contextualise <contextualise@noreply.github.com>
Cc: Farayi Chambati <flchambati@hotmail.com>; Mention <mention@noreply.github.com>
Subject: Re: [brettkromkamp/contextualise] Implement topics index (#17)


@navigator8<https://github.com/navigator8> Also, take a look at the Knowledge Graph Radar to see which other applications could be of use to you (to map knowledge): https://github.com/brettkromkamp/knowledge-graph-radar#applications

**Comment by navigator8** [comment]
Thanks for the Notes point. I  will start using this until we have an index of the ontology.

Best regards,


________________________________
