### ISSUE TITLE
Any plans to Dockerize contextualise?

### ISSUE THREAD

**Issue by machawk1** [brettkromkamp/contextualise#2]
This might help with users' system dependencies and get them up-and-running quicker.

/cc @ibnesayeed

**Comment by brettkromkamp** [comment]
I would love to have Contextualise dockerized. I just don't have the know-how.

**Comment by ibnesayeed** [comment]
I quickly looked at it and could not find the documentation about how to run it after cloning and installing dependencies. I can perhaps dig deeper and figure that out, but if it was documented in the README, it would have been very helpful. Once we know what is needed to run it and how the state/data is persisted, then Dockerizing it would not be difficult, you can expect contributions for that.

**Comment by brettkromkamp** [comment]
@ibnesayeed I will document, of course :)

**Comment by brettkromkamp** [comment]
@ibnesayeed For what it is worth, I have provided some more info with regards to installing the application (and its dependencies) in the [documentation](https://github.com/brettkromkamp/contextualise#install-the-development-version).

**Comment by ibnesayeed** [comment]
I think, the documentation is still missing necessary details on running it. I get that one needs to install it using pip (utilizing setup.py) then there is an external DB that needs to be installed and setup, but then what? Is there a command that one needs to run to boot the application up? How does this instance of the application connects to the externally set up data base? Some of these questions might be irrelevant or certain steps might be too obvious for you, but someone not familiar with the internals of the project might struggle with these.

**Comment by brettkromkamp** [comment]
@ibnesayeed Okay, valid points. I will provide the necessary details. Thanks for pointing this out.
