### ISSUE TITLE
Micro service-based Docker setup

### ISSUE THREAD

**Issue by brettkromkamp** [brettkromkamp/contextualise#31]
Contextualise’s Docker support is still under development. What’s more, its current monolithic Docker setup should be refactored into a micro service-based setup for components such as PostgreSQL (database), Nginx (web-server), and so forth.

I really need help with this :)

**Comment by ripperdoc** [comment]
I experience some issues running the Dockerfile:
- TopicsDB is not installed with it
- The CMD command is not starting Postgres so there is no database when run. It should probably be `/etc/init.d/postgresql start &&` before as long as it's monolithic?
- Access rights are not setup to store data in the `/contextualise/static/resources` path within the Docker-file, so no uploads work (and creating a map seem to require an image to be uploaded).

(I could possibly help out with a better Docker setup, as I'm running a Flask setup with DB and Nginx myself, but depends when I can allocate time.)

**Comment by brettkromkamp** [comment]
@ripperdoc Yes, the Current Docker setup is not working properly. I would dearly appreciate any assistance you could provide with regards to Docker, but I fully understand that there are only so many hours in a day :) No stress.
