### ISSUE TITLE
Hypergraphs?

### ISSUE THREAD

**Issue by lagleki** [brettkromkamp/contextualise#33]
Allow edge to connect more than two nodes.

**Comment by brettkromkamp** [comment]
> Allow edge to connect more than two nodes.

@lagleki The underlying topic maps engine supports exactly that: allowing an edge to connect to more than two nodes. Nonetheless, for the sake of simplicity in the user interface, Contextualise limits associations to just two topics/nodes. I could add an advanced UI to allow for edges to connect to more than two nodes. Food for thought!

**Comment by brettkromkamp** [comment]
Done and deployed.
