### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by nomatica** [brettkromkamp/contextualise#4]
Would love to see this on windows as a standalone app, but it looks like you might be going another direction.

**Comment by brettkromkamp** [comment]
@nomatica Yes, Contextualise is implemented as a web application. At some point (in the not too distant future) I will make it publicly available (at https://contextualise.io). Would you consider using it?

**Comment by nomatica** [comment]
While not proficient in this sort of thing, I understand enough to know how developing this as a web application makes a lot of sense. While I would be supportive and experiment with it, I really am looking for something that runs locally on my PC. It is a matter of privacy, and the cost of having many terabytes of data online. 

As I mentioned I am not proficient in these sort of things, but have managed to run a nextcloud instance in the past.   I have also experimented with cloudron.  If the web app were made very easy to implement I would try.
I am interested  its cataloging, relational and semantic search possibilities.

This sounds like a very cool project.

**Comment by brettkromkamp** [comment]
@nomatica Thanks for your feedback and enthusiasm (for the project). It's genuinely appreciated and helps with motivation :)

**Comment by nomatica** [comment]
It is a good project.  Will follow along.

**Comment by vladimirkosolapov** [comment]
This is a great project and it would be great to see it in a standalone application for offline use.

**Comment by brettkromkamp** [comment]
@vladimirkosolapov I'll keep in the back of my head. The current implementation of Contextualise is definitely web. Nonetheless, if there was sufficient demand for a desktop version I would at least consider it.

**Comment by machawk1** [comment]
@brettkromkamp [pyinstaller](https://www.pyinstaller.org/) is an option to "freeze" Contextualize into a native desktop app. I've used it to release Python based .app/.exes for some [software I've developed in the past](https://github.com/machawk1/wail).

With that said, I am also still working on getting it working on my desktop machine (been short on cycles) but the dependency chain makes this more fit for Dockerization (#2) than a stand-alone app. Even if everything is running on your own machine and available via a browser-based Web interface, it might suffice @nomatica's desire for privacy.

**Comment by brettkromkamp** [comment]
@machawk1 Yes, implementing Contextualise as a desktop application would be a huge undertaking and not something I would do lightly. If I did, I could use TopicDB almost as-is, just need to swap out PostgreSQL with something like SQLite. For the actual GUI toolkit I would use something like wxPython or PyQT (both of which I have experience with). But, again... I would only consider going down this road if there were a lot of people asking for it. Dockerizing the application is, by a wide margin, the preferred option :)

**Comment by nomatica** [comment]
@brettkromkamp I just want to say once again that I totally understand that it would be a huge undertaking.  It is hard for me to give my take on the demand, until I have see it and used it.  We live in a world where saas and server based "solutions" saturate the market.  Server solutions are a niche market. A stand alone desktop application can be used by anyone. I say this with the upmost respect of what you are doing.  I will follow the project and likely try and get it running when it is more mature. 

@machawk1 Very cool to see your interest in this project.  I actually ran across and played with WAIL a while ago and I have suggested it to some people.  There was a firefox plugin called Scrapbook,  I used for close to 10 years to save web pages.  During that 10 years there were several times when it broke and I went looking for options.  It finally died with Firefox killing off legacy apps, and I have been using Zotero.  Again not nearly as good as WAIL as the content is not identical.  But Zotero has a pretty good search, and I can take notes, and information can be found via desktop search.  

Thanks for ponging out pyinstaller

**Comment by machawk1** [comment]
@nomatica One of the barriers in creating a native app is having to manually code up the UI and then debug cross-platform issues if applicable. One option is for contextualise to be a native, double-clickable app with the UI still being web based.

Also glad to hear you know of [WAIL](https://github.com/machawk1/wail)! We [rewrote it in Electron](https://github.com/n0tan3rd/wail) as well with a slightly different stack but are still maintain the Python version, as it bundles institutional grade tools (e.g., [OpenWayback](https://github.com/iipc/openwayback), [Heritrix](https://github.com/internetarchive/heritrix3)).

Years back I also co-developed the (now defunct) [ArchiveFacebook](https://github.com/oduwsdl/archivefacebook) Firefox extension that used Scrapbook as its codebase! When Firefox moved from XUL to WebExtensions, we sunsetted it. We also got a cease and desist from Facebook for using that name, but that was after a couple of years of it being out and is beside the point. ;)

There are a few other packages that allow one to "freeze" python code like py2exe and py2app but PyInstaller seems to have the best support for cross-OS development and the linker is really good at bundling dependencies.

**Comment by brettkromkamp** [comment]
@nomatica It’s my intention to publish Contextualise (https://contextualise.io) as soon as possible. Saying that, it could still be a couple of weeks before that actually happens. I’ll keep people posted.

**Comment by brettkromkamp** [comment]
Application is publicly available, here: https://contextualise.dev/. A stand-alone app is not actively been considered.
