### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by zhuliangbing** [brettkromkamp/contextualise#53]
I  have created a new topic map. When adding a new topic, the following error appears:
————————————————————————————————
Internal Server Error
Something has gone wrong. Get in touch with Support if the problem persists. Find your way back home.

**Comment by brettkromkamp** [comment]
I cannot reproduce the error after creating a new topic map and adding a topic to it. I'll review the error logs. Perhaps you could record a quick screen cast in which you reproduce the error? Just to be sure... this was over at https://www.contextualise.dev/ or have you installed Contextualise and the error happened locally?

**Comment by brettkromkamp** [comment]
@zhuliangbing What fields are you providing? Topic name, the (generated) topic identifier and perhaps the topic's text? Any changes to the default advanced settings? Are you using a language other than English? Anyway... any additional info to try to determine what the problem is would be great :)

**Comment by zhuliangbing** [comment]
when I create a new topic at https://contextualise.dev whether it's a new Chinese or English topic,there is a "Internal Server Error".See attachment screenshot for details，please.Thank you very much! &nbsp; Liangbing Zhu


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Brett Alistair Kromkamp"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月5日(星期四) 凌晨1:42
收件人:&nbsp;"brettkromkamp/contextualise"<contextualise@noreply.github.com&gt;;
抄送:&nbsp;"剑魂"<272999579@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [brettkromkamp/contextualise] Internal Server Error (#53)




I cannot reproduce the error after creating a new topic map and adding a topic to it. I'll review the error logs. Perhaps you could record a quick screen cast in which you reproduce the error? Just to be sure... this was over at https://www.contextualise.dev/ or have you installed Contextualise and the error happened locally?

**Comment by brettkromkamp** [comment]
@zhuliangbing I don't see the attachment. But, regardless, just attempting to create a topic should obviously not cause an error. Problem is that I cannot reproduce and I am seemingly not seeing anything out of the ordinary in the (error) logs. But, I'll take a closer look at this part of the code base (https://github.com/brettkromkamp/contextualise/blob/edf70f7c35bb9c6efccd0bdd4bb5ccb6a025743d/contextualise/topic.py#L199) and see if I can see anything suspicious :)

**Comment by brettkromkamp** [comment]
@zhuliangbing Although I haven't found anything specific that is causing the bug you've described I have refactored the code in this part of the application a bit. Could you try again to create a topic and let me know if it still fails?

**Comment by zhuliangbing** [comment]
@Brett，When I create a new topic, I still report an error as follows:

Internal Server Error

Something has gone wrong. Get in touch with Support if the problem persists. Find your way back&nbsp;home.

URL：https://contextualise.dev/topics/edit/4/home

——————————————————————————————————————————————————————————————


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Brett Alistair Kromkamp"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月8日(星期天) 下午2:56
收件人:&nbsp;"brettkromkamp/contextualise"<contextualise@noreply.github.com&gt;;
抄送:&nbsp;"剑魂"<272999579@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [brettkromkamp/contextualise] Internal Server Error (#53)




@zhuliangbing Although I haven't found anything specific that is causing the bug you've described I have refactored the code in this part of the application a bit. Could you try again to create a topic and let me know if it still fails?

**Comment by brettkromkamp** [comment]
@zhuliangbing Very frustrating (as I cannot reproduce the bug). Could you signup (i.e., create a new user) and try again and see if the problem persists?

**Comment by brettkromkamp** [comment]
Not reproducible.
