### ISSUE TITLE
Support for SQLite

### ISSUE THREAD

**Issue by kseistrup** [brettkromkamp/contextualise#66]
Please consider support for SQLite (or ODBC/DBI) so that the app can run with something else than PostgreSQL.

Thanks!

**Comment by navigator8** [comment]
I second this. - as I would like to run the TopicDB Library on mobile using an app like Pythonista to create a personal knowledge graph.

I recall - you used to a NoteMapper app on Google store.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by brettkromkamp** [comment]
@navigator8 Yes, I had an Android app called NotesMappr on the Play Store. Blast from the past... must be close to 9-10 years ago, now.

**Comment by navigator8** [comment]
🙂 I actually bought a cheap android device to test how NoteMapper works. I could not find and still cannot find  TopicMaps/Graph based apps on ios.

________________________________

**Comment by brettkromkamp** [comment]
@kseistrup Why wouldn’t you just use The application at https://contextualise.dev/? Or, do you want to run it locally so as to not have to depend on having internet access?

**Comment by kseistrup** [comment]
@brettkromkamp Yes, I intended to self-host the app.

**Comment by brettkromkamp** [comment]
@kseistrup Contextualise can be run with Docker. Have you given that a try?

**Comment by kseistrup** [comment]
@brettkromkamp I can't say that I have (I'm not a big fan of dockerizing everything). But even if it ran in Docker I would still have to deal with PostgreSQL, wouldn't I? That's what I would like to avoid.

**Comment by brettkromkamp** [comment]
@kseistrup You wouldn't really have to deal with PostgreSQL, no. [Docker Compose](https://docs.docker.com/compose/) allows for defining and running multi-container Docker applications. In the case of Contextualise, the [docker-compose.yml](https://github.com/brettkromkamp/contextualise/blob/master/docker-compose.yml) has configured the PostgreSQL container and how it interacts with the rest of the application for you. Running Contextualise in Docker will set up everything including Contextualise's dependencies (like PostgreSQL).

**Comment by kseistrup** [comment]
@brettkromkamp I know that I am an old geezer and an outlier, but that doesn't sound appealing to me at all. Before even considering dockerizing everything, I would look for alternatives to Contextualise.

You shouldn't spend your valuable time on me. I will certainly love to see this issue closed and have Contextualise run with SQLite, but it's also too easy for me to suggest such a change because I don't know the inner workings of Contextualise and have no idea how much work will be involved. But I also don't want you to squander your resources.

**Comment by brettkromkamp** [comment]
@kseistrup No worries. You are definitely not squandering my resources. I would just like for you to be able to self-host the app and Docker allows for that. With regards to a SQLite version of TopicDB and by extension Contextualise, you are definitely not the first person to ask for something along those lines so I am considering how I would go about that. Obviously, this would take some time so I wouldn't want you to hold your breath :) But, I insist... you are not taking up any of my time and I will keep this issue open so that other people can see it and comment on it and we take things from there.

**Comment by kseistrup** [comment]
@brettkromkamp I'm glad to hear that. I won't hold my breath, but I will certainly keep an eye on the project. Thanks for your time so far, I really appreciate it.

**Comment by brettkromkamp** [comment]
@kseistrup Take a look here (if you haven't already) for a list of knowledge management applications that could be of interest for you: https://github.com/brettkromkamp/knowledge-graph-radar#applications. Several of them are open-source and I imagine can be self-hosted.

**Comment by kseistrup** [comment]
@brettkromkamp That's an impressive collection. Thanks a lot!

**Comment by kseistrup** [comment]
Amazing!!
