### ISSUE TITLE
[Potential Bug] Cannot delete Notes  or edit notes - that are not attached to any topic

### ISSUE THREAD

**Issue by navigator8** [brettkromkamp/contextualise#71]
Cannot delete Notes  or edit notes - that are not attached to any topic

**Comment by brettkromkamp** [comment]
@navigator8 Truth be told... I have forgotten to implement these two actions :O I will implement the functionality to edit and delete "unattached" notes over the next day or two.

**Comment by brettkromkamp** [comment]
Done and deployed. Thanks for reporting the issue.
