### ISSUE TITLE
AttributeError AttributeError: module 'mistune' has no attribute 'html'

### ISSUE THREAD

**Issue by brizzbane** [brettkromkamp/contextualise#74]
This is my first time using contextualise.

Got it installed, created my first map.  Then I went to edit the 'Home' topic for my map.  I pasted in markdown text from a TiddlyWiki entry I had made.

It immediately went to this error page, and now when I go to 'view map', this same error page shows up.

```
AttributeError
AttributeError: module 'mistune' has no attribute 'html'

Traceback (most recent call last)
File "/home/brizz/Server/contextualise/.env/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "/home/brizz/Server/contextualise/.env/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "/home/brizz/Server/contextualise/.env/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/brizz/Server/contextualise/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/home/brizz/Server/contextualise/.env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/home/brizz/Server/contextualise/.env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/brizz/Server/contextualise/.env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/brizz/Server/contextualise/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/home/brizz/Server/contextualise/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/home/brizz/Server/contextualise/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/brizz/Server/contextualise/contextualise/topic.py", line 136, in view
occurrences["text"] = mistune.html(occurrence.resource_data.decode())
AttributeError: module 'mistune' has no attribute 'html'
```

the last of the traceback:

```
File "/home/brizz/Server/contextualise/contextualise/topic.py", line 136, in view
        "notes": [],
    }
    for occurrence in topic_occurrences:
        if occurrence.instance_of == "text" and occurrence.scope == session["current_scope"]:
            if occurrence.resource_data:
                occurrences["text"] = mistune.html(occurrence.resource_data.decode())
        elif occurrence.instance_of == "image":
            occurrences["images"].append(
                {"title": occurrence.get_attribute_by_name(
                    "title").value, "url": occurrence.resource_ref, }
            )
AttributeError: module 'mistune' has no attribute 'html'
```

I tried uninstalling/reinstalling mistune with pip.  ..no luck.

I created a new map, and just typed '123' in the topic edit--and reached the same page.  So I'm wondering if maybe I screwed up install process somewhere?

Any help/guidance you can provide would be much appreciated.

**Comment by brettkromkamp** [comment]
@brizzbane Could you check what version of Mistune you have installed with `pip list | grep 'mistune'`?

If it anything other than 2.0.0a4 uninstall it with `pip uninstall mistune` and install the latest version (2.0.0a4) with `pip install mistune==2.0.0a4`. 

That should fix the problem. Please let me know either way.

**Comment by brizzbane** [comment]
Yea I just came back to say I checked requirements.txt file... and my mistune version was wrong.  I'm not sure how that happened...  I did have some errors when running the initial install (pip install -e .) --related to needing apt-get isntall libpq-dev.. so I re-ran pip install -e . a few times.  

I did:

```
pip uninstall mistune
pip install mistune==2.0.0a4
```

and that fixed it.

Thank you so much for your super quick reply!

**Comment by brettkromkamp** [comment]
@brizzbane You're welcome. If you have any questions (or hit any other bugs), just let me know :)

**Comment by brizzbane** [comment]
@brettkromkamp --since you offered :P

...how do you link to another topic (say "blah") w/in contextualise, (using markdown).  I'm assuming linking [blah](http://127.0.0.1:5000/topic/s/view/blah/1) isn't the right way to do it.

I'm super newb to this.  ...If I am asking this question, is contextualise maybe 'too much' for what I'm wanting to do?  (I love TiddlyWiki, ....but I also LOVE Python, and contextualise's multi-user capabilities..)

I've been looking for a minute now through docs/and the demo of contextualise.  I would have just viewed the source of the topic to see how you do it--but I can't, since I'm not a user.

Sorry for so much text.  Is my question clear?

**Comment by brettkromkamp** [comment]
You almost had it right [link-title](topic-identifier).

If you take a look at this page: https://www.contextualise.dev/topics/view/1/home

The second link (the one to "topic maps"... in Markdown it's just: `[topic maps](topic-maps)` with  "topic maps" being the link text and "topic-maps" being the identifier of the topic I am linking to: https://www.contextualise.dev/topics/view/1/topic-maps.

At some point I will add auto-complete/type-ahead for topic identifiers in the Markdown editor. Just haven't got around to it.

You can see the topic identifier for a topic by either looking at the URL bar: the topic identifier is the last part of the URL (in bold): https://www.contextualise.dev/topics/view/1/**topic-maps** 

Or, you can expand the topic properties panel (see screen snippet, below) by clicking on the "Properties" link next to the date just below the topic name.

![contextualise-topic-identifier](https://user-images.githubusercontent.com/160078/83339567-8f0ac880-a2cf-11ea-9455-493c4b6dfdd9.png)

**Comment by brizzbane** [comment]
lol--was just going to reply with this below ... and then your reply appeared.  thank you!

> @brizzbane You're welcome. If you have any questions (or hit any other bugs), just let me know :)

an example of what I am wondering how to do, look here:

https://contextualise.dev/topics/view/1/home

at the above site what is the proper way to link to "topic-maps".  I'm hoping that it isn't just a hard  link to exact url? ...that there is some way to actually link so that if topics-maps was renamed, the link would reflect that change w/out you having to update the text in view/1/home ...

**Comment by brettkromkamp** [comment]
Renaming the topic will not break the link in the Markdown. Topic names are independent of the topic's **identifier**. However, once you have created a topic (with an accompanying identifier), you cannot modify the identifier. In programming terms, the topic identifier is a _constant_.

**Comment by brettkromkamp** [comment]
By the way, Contextualise (and topic maps-based systems in general) are more formal than (back)links-based systems like Roam and TiddlyWiki. So, you might not find Contextualise as straight-forward as those applications. Also, to get the most out of Contextualise, you really do need to have (at least) a basic understanding of how topic maps work. Otherwise Contextualise working with Contextualise could be a frustrating experience. YMMV.

You might want to take a look at the Knowledge Graph Radar, as well: https://github.com/brettkromkamp/knowledge-graph-radar

**Comment by brettkromkamp** [comment]
Here are a couple of good resources explaining topic maps:

- https://docs.microsoft.com/en-us/previous-versions/aa480048(v=msdn.10)?redirectedfrom=MSDN
- https://ontopia.net/topicmaps/materials/tao.html

**Comment by brettkromkamp** [comment]
@brizzbane If you have any questions with regards to using Contextualise, just let me know.
