### ISSUE TITLE
Default Topics that come each new map

### ISSUE THREAD

**Issue by navigator8** [brettkromkamp/contextualise#76]
Kindly share in a blog  etc the topics / roles / associations that are in the database of a map by default.

**Comment by brettkromkamp** [comment]
@navigator8 The list of default topics is here: https://github.com/brettkromkamp/topic-db/blob/master/topicdb/core/store/topicstore.py#L52

**Comment by navigator8** [comment]
Many thanks! That will help me create my maps and take advantage of defaults.

**Comment by brettkromkamp** [comment]
@navigator8 I’m working on an “import” feature that will allow for topic creation and setting up the  relevant associations between the topics. The input file would look something like this:

```
python-programming-language
    expert-level-python
        meta-classes
        protocol-oriented-data-model
        decorators
        generators
            iterators
        context-managers
        asynchronous-io
    web-development
        web-development-frameworks
            wsgi
            asgi
        django-framework
        flask-framework
    machine-learning
    data-analysis
```

So, all of the necessary associations would be created to not only create the structure itself but also set up all of the knowledge/navigational paths, as well (as described, here: https://brettkromkamp.com/posts/knowledge-paths/).

**Comment by brettkromkamp** [comment]
The format shown above will be extended with the ability to optionally provide the topic name, type and tags.

**Comment by brettkromkamp** [comment]
@navigator8 I’m open for suggestions with regards to additional default topics.

**Comment by navigator8** [comment]
Let me have a good review and I will propose  some if at all!

**Comment by navigator8** [comment]
@
> @navigator8 I’m open for suggestions with regards to additional default topics.

This could be my biased view of how I work with Topic Maps (Social network analysis etc). Most them involve these entities:

Personal Information Management Objects
             * Agent
             ** Organisation
             ** Person
             ** Animal (e.g.could be pet - I know you grew up with dogs :))
             ** Group (i.e. Group of Organisations (Educations/ Medical) / Group of People)
             * Collection (collection of anything really - links / documents etc...)
             * Location
             ** Buidling
             ** City
             ** Country
             * Item (non living thing - this could be product/ etc
             * Process
             ** Project
             ** Task
             ** Event
             *** Social Event (e.g. Party)
             *** Formal Event (e.g. meeting)
