### ISSUE TITLE
Add feedback form

### ISSUE THREAD

**Issue by brettkromkamp** [brettkromkamp/contextualise#79]
Questions:

1. How would you feel if you could no longer use Contextualise?
    * Very disappointed
    * Somewhat disappointed
    * Not disappointed
2. What type of people do you think would most benefit from Contextualise?
3. What is the main benefit you receive from Contextualise?
4. How can I improve Contextualise for you?

**Comment by navigator8** [comment]
See answers in line.

________________________________

**Comment by brettkromkamp** [comment]
Added link to survey to top menu on the landing page (might need to make it more prominent).

**Comment by brettkromkamp** [comment]
Done.
