### ISSUE TITLE
Quick association creation UX

### ISSUE THREAD

**Issue by brettkromkamp** [brettkromkamp/contextualise#80]
Add the ability to quickly create an association. Perhaps this will end up being a modal dialog with one field to provide the "destination" topic. This would imply that the associations panel is dynamically populated (with an accompanying backend endpoint). Might be time to adopt [Vue.js](https://vuejs.org/) and build an associations component. 

@navigator8 This issue is of interest to you.

**Comment by navigator8** [comment]
Definitely, I am keen on this. It will allow frictionless linking and knowledge discovery!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by brettkromkamp** [comment]
@navigator8 Have started working on this issue. Might take a bit of time, I need to learn https://svelte.dev/ to implement the dynamic associations component. Will be fun :)

**Comment by navigator8** [comment]
This is music 🎵 to my ears!

I cannot wait to test drive it!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by brettkromkamp** [comment]
This feature consists of several parts:

1. API endpoint to retrieve the association groupings (effectively replacing what is currently done by means of a Jinja2 template)'
2. Modal dialog with the association (creation) form
3. API (POST) endpoint to create an association (called by submitting the form from step 2)
4. The ability to edit associations - the associations created with the "quick association creation" UX will be very generic (of type "association" with both the source and destination roles being "related"), so it is quite likely that at some point, the user will want to edit these associations (type, roles, etcetera).

**Comment by brettkromkamp** [comment]
@navigator8 Implementation is in place. But, this feature is made up of several parts so I'll do some testing during the day. If all good, then I will deploy either later this evening or early tomorrow morning.

**Comment by navigator8** [comment]
Wow! busy weekend hey! looking forward to have a play when ready. Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by brettkromkamp** [comment]
Adding a generic association is done by clicking on the `Association `menu followed by choosing the` Create generic association` menu option. Once a topic is referenced in an association (that is, it has related topics), you can also click on the `Create association` link above the related topics panel (outlined in red in the screenshot below).

![contextualise-quick-association1b](https://user-images.githubusercontent.com/160078/87389633-5dac3a80-c5a7-11ea-8fd3-d2642ed12dca.png)

Creating the association is done by providing the topic reference for the "destination" topic (see screenshot below).

![contextualise-quick-association2](https://user-images.githubusercontent.com/160078/87389681-787eaf00-c5a7-11ea-920a-d232d283b541.png)

**Comment by brettkromkamp** [comment]
@navigator8 Deployed. But, this has been a bit of a tricky feature to implement, specifically with regards to the new (Vue.js) dynamic associations component and scope filtering. So, let me know if you come across any weird behaviour :)

**Comment by navigator8** [comment]
@brettkromkamp Judging from the screenshot - it's going to be tons easier to create a network of ideas. I will certainly give it play tomorrow morning and feedback.

**Comment by brettkromkamp** [comment]
Might even add a shortcut command to open the dialog.

**Comment by brettkromkamp** [comment]
@navigator8 Talking about feedback :) In general what is your opinion of Contextualise? Especially taking into account all of the other applications in this space... What is good about Contextualise? What is bad? What could be improved? No rush, though :)

**Comment by zhlbb** [comment]
I like this software very much, do not know when will release official v1.0 version? It is recommended to write a detailed installation and user manual, thank you!

**Comment by brettkromkamp** [comment]
@zhlbb Thanks for your feedback. With regards to your suggestion about a user guide (documentation), I have added an issue for it: https://github.com/brettkromkamp/contextualise/issues/86.

The "official" release of version 1.0 is planned for August 25 (but, will probably be later) and can be tracked, here: https://github.com/brettkromkamp/contextualise/milestone/1.

Anyway, if you have any further suggestions with regards to Contextualise, I would love to hear them :)

**Comment by brettkromkamp** [comment]
Done.
