### ISSUE TITLE
Combine all information resources into one tab with filtering by (occurrence) type

### ISSUE THREAD

**Issue by brettkromkamp** [brettkromkamp/contextualise#83]
Currently, images, 3D scenes (glTF files), files, links and videos all have their own separate (top-level) tab. The plan is to combine all of the topic occurrences into one top-level tab with filtering by occurrence type (`instance of`). The resulting top level  would be: 1) topic, 2) resources, 3) associations and 4) visualisations.

**Comment by brettkromkamp** [comment]
**Done. Won't close yet (hoping to get some feedback)**.

![contextualise-top-level-menu](https://user-images.githubusercontent.com/160078/86622429-298db400-bfc0-11ea-9645-82d76d295b5b.png)

![contextualise-top-level-menu-collapsed-resources](https://user-images.githubusercontent.com/160078/86622442-2d213b00-bfc0-11ea-8936-59925e8a9f8f.png)

@navigator8 Heads up... some (UX) changes to the top-level menu: all occurrences (i.e., information resources: images, 3D scenes, links, files and video links have been combined into one: Resources). It's just a UX/UI change.

**Comment by brettkromkamp** [comment]
Done!

**Comment by navigator8** [comment]
@brettkromkamp I realise this topic is closed. Whilst I was asleep! Time zone magic. One comment - I love the simplification. How do you view notes relative to topics? The reason I ask if we add multiple notes on Topic - I tend to view them as occurrences- hence Resources.

**Comment by brettkromkamp** [comment]
@navigator8 Yes, I closed the issue somewhat prematurely. Sorry for that. I appreciate your opinion on these things.

Glad you like the simplification. This is more scaleable as more occurrence types are added. And, I think it makes sense to group the occurrences together.

With regards to notes... they are occurrences as you mentioned. It's just that there is a bespoke UI for them (below the topic text). But, it might make sense to also add them to the occurrences tab now that it's there.
