### ISSUE TITLE
Test collaboration feature

### ISSUE THREAD

**Issue by brettkromkamp** [brettkromkamp/contextualise#90]
The collaboration feature on maps needs to be properly tested. Ideally, this testing is done by two separate users (the map owner and the person with whom is being collaborated with).

The collaboration feature allows topic map collaboration in three distinct modes (all of which need to be separately tested):

- Can view (read-access only)
- Can comment (add notes to existing topics)
- Can edit (read/write access)

@navigator8 Would you be up for testing this feature with me? If yes, then I would need to know the email address you used to sign up with to Contextualise (collaboration is set up by providing the email address of the person you want to collaborate with).

**Comment by navigator8** [comment]
@brettkromkamp  been waiting for this feature! I have sent my email via Twitter DM.

Best regards,

**Comment by brettkromkamp** [comment]
@navigator8 Thanks! I will add you as a collaborator to a map. You should see the map you've been added to (as a collaborator) in the "Maps I am collaborating on" tab in the "My map" view. I'll send you a (follow-up) message when ready. We'll test in the order outlined above (i.e., can view, can edit, can comment). I'll provide somewhat more in-depth "instructions" for each phase of testing. By the way, please call me Brett :)

**Comment by brettkromkamp** [comment]
@navigator8 I have already come across one (logical) bug. The new associations component allows you to create a quick/generic association in can-view (read-only) collaboration mode. I will fix that before we start testing.

**Comment by navigator8** [comment]
Hi Brett! 
Woke to a new map in [My Maps I am collaborating on] !

**Comment by brettkromkamp** [comment]
Morning Farayi. Yep, I've added you as a collaborator to a map. You should have seen something similar to this:
![contextualise-collaboration1](https://user-images.githubusercontent.com/160078/88252890-224cf280-ccb0-11ea-9d3b-664a332a79d4.png)

The collaboration mode is "Can view" (read-only) so you should be seeing something similar to this (inside of the map):
![contextualise-collaboration2](https://user-images.githubusercontent.com/160078/88252923-46a8cf00-ccb0-11ea-9806-185208ed2583.png)

You can navigate around the map, including accessing the "visualisations" like the network graph and the recently added tag cloud. You should not be able to do anything beyond that.

**Comment by navigator8** [comment]
Hi Brett! too late with these instructions :). I have already jumped in and tried to to create topics/ associations. Not possible in view mode.

**Comment by brettkromkamp** [comment]
Ok, yes... it's just to confirm that you cannot do anything you would expect not to be able to do in a read-only mode. Then the next test would be to change the collaboration mode to "Can comment". This is almost the same as the "Can view" (read-only) mode but you can also add notes (i.e., comments) to existing topics. Nothing more, though. 

So, let me know if when you have finished testing the "Can view" (read-only) mode and I will change your collaboration mode on this map to start the next round of testing :)

**Comment by navigator8** [comment]
Great stuff! I had a good play in the morning! I am about 10hours ahead of Norway 🇳🇴:). Upgrade my privileges to “ Can comment”.

Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by brettkromkamp** [comment]
Will do!

**Comment by navigator8** [comment]
Hi Brett, I have added a few notes using different tests. One suggestions - are you able to add a label [user id etc]  to show who has added the comment/note.  This will well to see who has contributed what. You could even go a step further to show a by different colours, i.e. note border by owner/admin (one colour) and another colour for contributors.

**Comment by brettkromkamp** [comment]
Good suggestion, Farayi. I'll take a look at implementing it. With regards to linking to other topics in in both normal topic text and notes... it's obviously possible. The syntax is the usual Markdown link syntax: `[the link's text](the-topic-identifier)`. You don't have to specify the full URL, just the topic identifier for the topic you are linking to (Contextualise will infer the rest of the URL). Let's say you want to link to the "Home" topic from another topic. The way to specify the link in the topic text or note would be: `[whatever link text you want to use](home)`.

**Comment by brettkromkamp** [comment]
@navigator8 Hi Farayi. In the meantime, do we move on to testing the third mode: "Can edit"?

**Comment by navigator8** [comment]
Hi Brett!

Yes, please this is the fun bit. Wait and see what network I will create :)!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by brettkromkamp** [comment]
Ok, you now have read-write access to the map. You should, be able to do everything: create, update and delete topics, occurrences and associations. Let me know how it goes :)

**Comment by brettkromkamp** [comment]
@navigator8 Hi Farayi. I'm assuming you have finished testing the "Can edit" collaboration mode, or? If yes, thanks a lot! There is just one final thing to test with regards to collaboration: removing you as a collaborator on the topic map and you confirming that you do not have access to the map anymore.

**Comment by navigator8** [comment]
Hello Brett!

Yes, I did some testing. Happy for you to remove me as a collaborator.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by brettkromkamp** [comment]
@navigator8 I have removed you as a collaborator. You shouldn't have access to the map anymore. Please confirm either way.

**Comment by navigator8** [comment]
Hi Brett

Ooops!  Map has disappeared  under [Maps I am collaborating on]]. Confirmed.

**Comment by brettkromkamp** [comment]
Excellent! Then I think we can conclude on the testing of the collaboration feature. Thanks for all of your help, Farayi! Really appreciate it!
